### ISSUE TITLE
The model files in ImageNet-1k Classification are mismatched

### ISSUE THREAD

**Issue by bestzsq** [ChenhongyiYang/GPViT#1]
Hello, Amazing for your excellent work!

The model files uploaded in  ImageNet-1k Classification table seem mismatched, the GPViT-L2 model is gpvit_l3_in1k_300e.pth; the GPViT-L3 and GPViT-L4 model are both gpvit_l4_in1k_400e.pth.

Thank you for your nice work！

**Comment by ChenhongyiYang** [comment]
Oh, sorry, my bad! It is not fixed!

**Comment by bestzsq** [comment]
Thanks for your reply, but I'm afraid that The GPViT-L2 model hasn't been fixed. which is gpvit_l3_in1k_300e.pth.

**Comment by ChenhongyiYang** [comment]
lol, sorry,  it is fixed now
